/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosNewRouteImport } from './routes/todos.new'
import { Route as ApiTodosRouteImport } from './routes/api.todos'
import { Route as TodosTodoIdEditRouteImport } from './routes/todos.$todoId.edit'
import { Route as ApiTodosTodoIdRouteImport } from './routes/api.todos.$todoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosNewRoute = TodosNewRouteImport.update({
  id: '/todos/new',
  path: '/todos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTodoIdEditRoute = TodosTodoIdEditRouteImport.update({
  id: '/todos/$todoId/edit',
  path: '/todos/$todoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosTodoIdRoute = ApiTodosTodoIdRouteImport.update({
  id: '/$todoId',
  path: '/$todoId',
  getParentRoute: () => ApiTodosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/todos/new': typeof TodosNewRoute
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/todos/new': typeof TodosNewRoute
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosRouteWithChildren
  '/todos/new': typeof TodosNewRoute
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/todos'
    | '/todos/new'
    | '/api/todos/$todoId'
    | '/todos/$todoId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/todos'
    | '/todos/new'
    | '/api/todos/$todoId'
    | '/todos/$todoId/edit'
  id:
    | '__root__'
    | '/'
    | '/api/todos'
    | '/todos/new'
    | '/api/todos/$todoId'
    | '/todos/$todoId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTodosRoute: typeof ApiTodosRouteWithChildren
  TodosNewRoute: typeof TodosNewRoute
  TodosTodoIdEditRoute: typeof TodosTodoIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/new': {
      id: '/todos/new'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$todoId/edit': {
      id: '/todos/$todoId/edit'
      path: '/todos/$todoId/edit'
      fullPath: '/todos/$todoId/edit'
      preLoaderRoute: typeof TodosTodoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos/$todoId': {
      id: '/api/todos/$todoId'
      path: '/$todoId'
      fullPath: '/api/todos/$todoId'
      preLoaderRoute: typeof ApiTodosTodoIdRouteImport
      parentRoute: typeof ApiTodosRoute
    }
  }
}

interface ApiTodosRouteChildren {
  ApiTodosTodoIdRoute: typeof ApiTodosTodoIdRoute
}

const ApiTodosRouteChildren: ApiTodosRouteChildren = {
  ApiTodosTodoIdRoute: ApiTodosTodoIdRoute,
}

const ApiTodosRouteWithChildren = ApiTodosRoute._addFileChildren(
  ApiTodosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTodosRoute: ApiTodosRouteWithChildren,
  TodosNewRoute: TodosNewRoute,
  TodosTodoIdEditRoute: TodosTodoIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
